# Generated by Django 5.1.5 on 2025-02-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0004_course_delete_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author_image',
            field=models.ImageField(upload_to='author/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course/'),
        ),
    ]
